[functions.push-notification]
enabled = true
verify_jwt = false

[functions.notify-animal-owner]
enabled = true
verify_jwt = false

[functions.checkout]
enabled = true
verify_jwt = false

[functions.stripe-webhook]
enabled = true
verify_jwt = false

[functions.contact-form]
enabled = true
verify_jwt = false
